version: '3.4'

services:
  
  shoppinglistms.api:
    image: ${DOCKER_REGISTRY-}shoppinglistms
    build:
      context: .
      dockerfile: ShoppingListMS/Dockerfile
    environment: 
      TZ: America/Sao_Paulo
    ports:
      - "5000:80"  
    networks: 
      - network-rodrigo
networks: 
  network-rodrigo:
    driver: bridge      