version: '3.4'

services:
  shoppinglistms.api:
    image: shoppinglistms:dev
    container_name: ShoppingListMS.Api
    build:
      target: runtime
      labels:
        com.microsoft.created-by: "visual-studio"
        com.microsoft.visual-studio.project-name: "ShoppingListMS.Api"
    environment:
      - DOTNET_USE_POLLING_FILE_WATCHER=1
      - ASPNETCORE_LOGGING__CONSOLE__DISABLECOLORS=true
      #- NUGET_FALLBACK_PACKAGES=$container_paths_to_fallback_packages_shoppinglistms.api$
    volumes:
      - /Users/rodrigoprado/Projects/ShoppingListMS/ShoppingListMS/ShoppingListMS:/app
      - /Users/rodrigoprado/Projects/ShoppingListMS/ShoppingListMS:/src
      - /Users/rodrigoprado/vsdbg/vs2017u5:/remote_debugger:rw
#$nuget_volume_mapping_shoppinglistms.api$

    entrypoint: tail -f /dev/null
    labels:
      com.microsoft.visualstudio.debuggee.program: "dotnet"
      #com.microsoft.visualstudio.debuggee.arguments: " $debuggee_arguments_probing_paths_shoppinglistms.api$ \"/app/bin/Debug/netcoreapp3.1/ShoppingListMS.dll\""
      com.microsoft.visualstudio.debuggee.workingdirectory: "/app"
      com.microsoft.visualstudio.debuggee.killprogram: "/bin/sh -c \"if PID=$$(pidof dotnet); then kill $$PID; fi\""
    tty: true